backend:
  name: github
  repo: kovvdn/productivity_app

collections:
  - name: products
    label: Products
    folder: src/data
    create: true
    fields: # The fields for each document, usually in front matter
      - { label: "Label", name: "label", widget: "string" }
      - {
          label: "Factor",
          name: "factor",
          valueType: "float",
          widget: "number",
        }

media_folder: static/assets
public_folder: /assets
