backend:
  name: github
  repo: kovvdn/productivity_app

collections:
  - name: post
    label: Posts
    folder: src/data
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }

media_folder: static/assets
public_folder: /assets
